### ISSUE TITLE
[1.20.1] World creation crash

### ISSUE THREAD

**Issue by Proxwian** [Arborsm/ArborCore#10]
[crash-2024-05-14_20.32.13-client.txt](https://github.com/Arborsm/GT--/files/15311931/crash-2024-05-14_20.32.13-client.txt)

Happening w/o CC: Tweaked, but there's no evidence mod requires it to be installed

**Comment by Arborsm** [comment]
oops fix it tomorrow



---Original---
From: "Anatolii ***@***.***&gt;
Date: Wed, May 15, 2024 01:33 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [Arborsm/GT--] [1.20.1] World creation crash (Issue #10)




 
crash-2024-05-14_20.32.13-client.txt
