### ISSUE TITLE
中子素混合粉配方错误

### ISSUE THREAD

**Issue by skyinr** [Arborsm/ArborCore#11]
mods:
gtnn-1.0.7
gtcum-1.2.3.a

![image](https://github.com/Arborsm/GT--/assets/41814896/eb4dadbc-3930-4ac9-a46e-321fc1fbfc81)
这是有意的游戏设计，还是纯粹的配方错误？

**Comment by Arborsm** [comment]
游戏设计，看它的相关配方应该是能正常转成中子锭的

**Comment by skyinr** [comment]
这个中子素混合物粉，能且仅能从精炼银的工作台锻造锤配方获得。
并且这个工作台锻造锤配方与原版的精炼银配方冲突，可能会影响ae自动化，建议重新设计一下这个粉的获取方式。

**Comment by Arborsm** [comment]
奇怪

**Comment by Arborsm** [comment]
我去看看

**Comment by Arborsm** [comment]
![image](https://github.com/Arborsm/GT--/assets/44860537/5ebf7bd5-69e1-4336-bc7c-d576cee7ac9c)
我这边没问题

**Comment by Arborsm** [comment]
你是整合包还是啥 应该是有什么把中子素粉的获取改了，我用的是替换法，所以应该不是我这边的问题

**Comment by skyinr** [comment]
很神奇，有时候会出现这个配方。有时候不会出现，而且这个配方每次出现的时候，用的精炼矿还不一样。
一个个mod加到最后这个配方都不会出现。但是一次性全加载这些mod就会出现。

感觉上是gtm配方生成的问题

测试所用mod:
gtceu-1.2.3.a
gtnn-1.0.7
monazite-1.20.1-1.1.5
kubejs-forge-2001.6.5-build.7
probejs-6.0.1-forge
rhino-forge-2001.2.2-build.18
architectury-9.2.14-forge
jei-1.20.1-forge-15.3.0.4

**Comment by Arborsm** [comment]
蛮怪的
