### ISSUE TITLE
美孚化工厂导致的渲染错误

### ISSUE THREAD

**Issue by skyinr** [Arborsm/ArborCore#14]
GTM版本为gtceu-1.20.1-1.3.0

日志：https://mclo.gs/uKMH4yi

**Comment by Arborsm** [comment]
更新



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月16日(周日) 晚上9:53
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Arborsm/GT--] 美孚化工厂导致的渲染错误 (Issue #14)




 
GTM版本为gtceu-1.20.1-1.3.0
 
日志：https://mclo.gs/uKMH4yi
