### ISSUE TITLE
Can't join the server after updating gtceu-1.20.1-1.3.0-a

### ISSUE THREAD

**Issue by ptk2003** [Arborsm/ArborCore#15]
after login and world loading get message "Internal Exception: java.lang.RuntimeException: Unknown element name:tf"

gtceu-1.20.1-1.3.0-a
gtnn-1.0.8b
1.20.1-forge-47.3.1

**Comment by ptk2003** [comment]
![image_2024-06-22_00-01-20-1](https://github.com/Arborsm/GT--/assets/28514017/aa13f362-1bc6-4a63-96f6-7279453c3eca)

**Comment by Arborsm** [comment]
![image](https://github.com/Arborsm/GT--/assets/44860537/c90ee612-e6ee-4c58-8fab-c1d417cf075c)
The issue is not on my side.

**Comment by Arborsm** [comment]
Wait a moment, let me try production env

**Comment by Arborsm** [comment]
yep not on my side

**Comment by ptk2003** [comment]
gtnn-1.0.8b was identified by exclusion (sequential removal of GT addons and other mods in a copy of the world).
The problem is not starting a clean / new world, but logging into a server with an existing world (after the GT update), where we have already built many machines (steam, LV and MV) from GT.

**Comment by ptk2003** [comment]
so re-add gtnn-1.0.8b in pack cause same error.
may be i can collect something debug information for help?

**Comment by Arborsm** [comment]
uhh

**Comment by Arborsm** [comment]
I am not sure why it comes up

**Comment by Arborsm** [comment]
could you sent the logs?

**Comment by ptk2003** [comment]
today we update gtceu-1.20.1-1.3.0-a to gtceu-1.20.1-1.3.1, 
when try add gtnn-1.0.8b get same error.
world on server side contain exitings machine from steam age and LV age.
all other mod was temporary removed for test.



[server_latest.log](https://github.com/user-attachments/files/16068546/server_latest.log)
[client_latest.log](https://github.com/user-attachments/files/16068551/client_latest.log)
connect in 15:52:40

**Comment by ptk2003** [comment]
now, with gtceu-1.20.1-1.3.1 + gtnn-1.0.8b i can not join on server with clear world with same error:
[15:57:45] [Netty Client IO #1/ERROR]: Unknown element name:tf

**Comment by ptk2003** [comment]
in local (single player) can join

**Comment by Kaguya154** [comment]
yeah,I got the same problem

**Comment by skyinr** [comment]
看起来这个bug是因为矿脉同步问题

测试所用mod:
gtceu-1.3.1 
gtnn-1.0.8b

需要使用外部专用服务器.使用localhost连接的专用服务器无法复现
我使用远程调试打到的断点如图
![image](https://github.com/Arborsm/GT--/assets/41814896/301d50ca-d77c-41ee-b837-aefe989268a5)

——————————
It seems that this bug is due to synchronization issues in vein generation

test mod:
gtceu-1.3.1 
gtnn-1.0.8b

External dedicated server is required. Dedicated servers connected using localhost cannot replicate

**Comment by Arborsm** [comment]
> 看起来这个bug是因为矿脉同步问题
> 
> 测试所用mod:
> gtceu-1.3.1 
> gtnn-1.0.8b
> 
> 需要使用外部专用服务器.使用localhost连接的专用服务器无法复现
> 我使用远程调试打到的断点如图
> ![image](https://github.com/Arborsm/GT--/assets/41814896/301d50ca-d77c-41ee-b837-aefe989268a5)
> 
> ——————————
> It seems that this bug is due to synchronization issues in vein generation
> 
> test mod:
> gtceu-1.3.1 
> gtnn-1.0.8b
> 
> External dedicated server is required. Dedicated servers connected using localhost cannot replicate
> 

thx, will check soon, kinda busy those days

**Comment by Arborsm** [comment]
try latest version in modrinth
