### ISSUE TITLE
当gtnn和ad astra一起用有两个bug

### ISSUE THREAD

**Issue by Qinlex479** [Arborsm/ArborCore#16]
![6$FFVMV$A RMR05 8B1DH9H](https://github.com/Arborsm/GT--/assets/137138443/50e0a410-b8d6-4f37-baf6-3f1b7de9a732)
游戏版本是1.20.1 Forge 47.2.0
当gtnn和ad astra一起用时末地会没有矿，什么矿都没有
![CHS3)WW{)1VY QCW@LVOW2Q](https://github.com/Arborsm/GT--/assets/137138443/36d7d0a0-0bfd-414f-8e8d-d37ab795c621)
如果单独使用gtnn末地矿物生成正常

第二个是有gtnn时，会导致ad的火箭燃料加不进去
![%PO0$3VLLAOC~GAGD@Z{LS7](https://github.com/Arborsm/GT--/assets/137138443/3d9adbc0-cd2c-420f-a60a-29a4301cf2d8)
如果单独使用ad则可以正常加燃料。

**Comment by Arborsm** [comment]
游戏设计， 末地矿被移到了adastra的星球里，燃料用的是gtnn的燃料

**Comment by Arborsm** [comment]
具体矿可以看jei， 以及我觉得我得给adastra的火箭加个注释
