### ISSUE TITLE
Placing ”Homemade Bedrock Ore Machine“ will cause the world to crash

### ISSUE THREAD

**Issue by lostmyself8** [Arborsm/ArborCore#18]
Placing ”Homemade Bedrock Ore Machine“ will cause the world to crash.
放置土质基岩矿机会导致世界崩溃。

Minecraft version: 1.20.1

**Added the following mod:**
Just Enough Items 15.3.0.8
GregTechCEu Modern 1.3.0-a
bad packets 0.4.3
Gregicality Rocketry 0.1.9
GT-- 1.0.8b
WTHIT 8.13.1

[crash-2024-06-29_22.41.39-server.txt](https://github.com/user-attachments/files/16040879/crash-2024-06-29_22.41.39-server.txt)

**Comment by Arborsm** [comment]
需要开启 gtm的基岩矿机和gtnn的空岛模式
