### ISSUE TITLE
"impure_enriched_naquadah_solution" recipe has too many fluid outputs

### ISSUE THREAD

**Issue by jmoiron** [Arborsm/ArborCore#25]
This recipe:

https://github.com/Arborsm/GT--/blob/57725523223d1b320b613292448db2abae132f55/src/main/java/dev/arbor/gtnn/data/recipes/NaquadahLine.kt#L251-L258

Is an EBF recipe that yields 2 fluids, but EBFs are limited to 1 fluid output:

https://github.com/GregTechCEu/GregTech-Modern/blob/1.20.1/src/main/java/com/gregtechceu/gtceu/common/data/GTRecipeTypes.java#L507-L508

**Comment by Arborsm** [comment]
oops

**Comment by jmoiron** [comment]
This blast recipe could yield 1 "enriched naquadah oxide mixture dust", which is already processable into the "impure enriched naquadah solution" in a chem reactor (1 dust -> 1 bucket) and loop to the normal nq+ processing chain

**Comment by Arborsm** [comment]
well I will turn it to chemical plant in next version
