### ISSUE TITLE
Use of copyrighted code and violation of Apache-2.0

### ISSUE THREAD

**Issue by AnOpenSauceDev** [Arborsm/ArborCore#3]
Hello there, just wanted to say that you're using copyrighted code within your project. In [this file](https://github.com/Arborsm/GT--/blob/loom/src/main/java/org/arbor/gtnn/mixin/client/ToastKiller.java), there is an almost 1:1 copy of my own code from Methane/The Open Sauce Toast Killer, especially in [earlier commits](https://github.com/Arborsm/GT--/blob/5eb288e3936122d64dba8cb89e17be926bf8b3d9/src/main/java/org/arbor/arborcore/mixin/Client/ToastKiller.java). I'm not angry or anything, and don't really care in this case (other implementations will use a similar method regardless), but you shouldn't copy blobs of code from other mods that are licensed! This is a sure-fire way to get your mod banned, as it directly violates Modrinth's content policy.

I'd recommend either leaving a notice about the use of copyrighted code, or to remove all offending versions with copyrighted code from other mod authors to prevent yourself running into potential legal troubles.

**Comment by Arborsm** [comment]
I apologize for this. The early version of this mod was merely a personal modification I used, and then, for the sake of convenience, I directly copied your code and forgot about its license after several commits.

**Comment by AnOpenSauceDev** [comment]
No problem! I was more warning you about what could happen with other mod devs.
