### ISSUE TITLE
no recipe for Na2NO3 in ATM9

### ISSUE THREAD

**Issue by woetal** [Arborsm/ArborCore#4]
![{32FB99F8-C189-43ea-AB55-D9B9EF2BF9E9}](https://github.com/Arborsm/GT--/assets/158049399/fb11e481-6bb6-4568-b17e-9ad1e5628977)

**Comment by Arborsm** [comment]
下新版本

**Comment by woetal** [comment]
[Uploading 2024-03-24-6.log…]()

**Comment by Arborsm** [comment]
> [Uploading 2024-03-24-6.log…]()
> 

？？ 看不见

**Comment by woetal** [comment]
HMCL出现了模组注入问题，使用版本gtnn 1.0.0c，我这个log没发出去

**Comment by Arborsm** [comment]
所以是没问题了吗

**Comment by woetal** [comment]
[minecraft-exported-logs-2024-03-27T13-04-33.log](https://github.com/Arborsm/GT--/files/14767910/minecraft-exported-logs-2024-03-27T13-04-33.log)

**Comment by woetal** [comment]
![image](https://github.com/Arborsm/GT--/assets/158049399/371d4dee-c3b6-4eee-81f2-fe06b0182a38)

**Comment by Arborsm** [comment]
是哪个版本的

**Comment by woetal** [comment]
GTM：1.1.3.b build_516
GTNN：1.0.0c

**Comment by woetal** [comment]
GTM我换新版本后会出现多方块结构卡合成0%的bug

**Comment by Arborsm** [comment]
更新gtnn和gtm 卡0%把设置里的使用vbo关了



---Original---
From: ***@***.***&gt;
Date: Wed, Mar 27, 2024 23:35 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [Arborsm/GT--] no recipe for Na2NO3 in ATM9 (Issue #4)




 
GTM我换新版本后会出现多方块结构卡合成0%的bug

**Comment by woetal** [comment]
![image](https://github.com/Arborsm/GT--/assets/158049399/8d61b793-7eb2-4337-9350-d0d8e324e0f8)
这个版本行吗

**Comment by Arborsm** [comment]
行 但是推荐用发布版本



---Original---
From: ***@***.***&gt;
Date: Thu, Mar 28, 2024 12:38 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [Arborsm/GT--] no recipe for Na2NO3 in ATM9 (Issue #4)




 
image.png (view on web)
 这个版本行吗

**Comment by woetal** [comment]
[Uploading minecraft-exported-logs-2024-03-28T21-21-53.log…]()

**Comment by woetal** [comment]
[minecraft-exported-logs-2024-03-28T21-21-53.log](https://github.com/Arborsm/GT--/files/14790215/minecraft-exported-logs-2024-03-28T21-21-53.log)
![image](https://github.com/Arborsm/GT--/assets/158049399/2092f90f-e55f-458b-aac7-3052108f9481)

**Comment by Arborsm** [comment]
看不出来

**Comment by woetal** [comment]
![image](https://github.com/Arborsm/GT--/assets/158049399/4a9ebef5-f544-49fe-b7a9-cd62232fe210)
然后这个不工作

**Comment by woetal** [comment]
![image](https://github.com/Arborsm/GT--/assets/158049399/1439a44c-482f-4b9a-ba8e-3764456c5447)

**Comment by Arborsm** [comment]
迟点看看

**Comment by woetal** [comment]
普通的tnt也不行，ITNT也不行

**Comment by Arborsm** [comment]
新版本

**Comment by woetal** [comment]
我不知道这是不是我这里的问题（
![image](https://github.com/Arborsm/GT--/assets/158049399/1d23caaf-1f00-4109-904f-05337618f708)
LuV机械方块+硅岩线圈显示配方处理等级是IV，但是要产凯金的话要LuV
![image](https://github.com/Arborsm/GT--/assets/158049399/38e31419-6444-4325-b2a1-ea9cc9df0ad1)
升级凯金和ZPM化工厂的话又需要凯金（

**Comment by woetal** [comment]
![image](https://github.com/Arborsm/GT--/assets/158049399/867773a7-33f5-470b-8e58-612820c4190e)

**Comment by woetal** [comment]
![image](https://github.com/Arborsm/GT--/assets/158049399/b371352c-5bca-478e-a095-1101755cdcba)

**Comment by Arborsm** [comment]
草 我等会去看看

**Comment by woetal** [comment]
浅问一下，大佬未来还会做其他NH的移植吗（小声）

**Comment by woetal** [comment]
> 浅问一下，大佬未来还会做其他NH的移植吗（小声）

就是类似gt--的，给1.20GTM用的

**Comment by woetal** [comment]
想玩NH的东西，但是NH难度还是大了，周期太长了（）

**Comment by Arborsm** [comment]
不知道，最近好忙 gtnn都没空写

**Comment by woetal** [comment]
ok

**Comment by woetal** [comment]
埃克森美孚化工厂的过氧化氢配方是不是有点问题（听别人说的

**Comment by woetal** [comment]
> 我不知道这是不是我这里的问题（ ![image](https://private-user-images.githubusercontent.com/158049399/318238432-1d23caaf-1f00-4109-904f-05337618f708.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNDU4MzAsIm5iZiI6MTcxMjA0NTUzMCwicGF0aCI6Ii8xNTgwNDkzOTkvMzE4MjM4NDMyLTFkMjNjYWFmLTFmMDAtNDEwOS05MDRmLTA1MzM3NjE4ZjcwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMlQwODEyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTY0ZGNiOTcyOGZjYjgyNjEzYzkxYjkwNjMzMzk0MWY1N2ViZTJhNWI4N2ViZmMzODIzZTk4MGExNTA0OTAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QO0Q1ede8BPwpsxBg6qVx70SSvCGzzILcPf1LKPQ428) LuV机械方块+硅岩线圈显示配方处理等级是IV，但是要产凯金的话要LuV ![image](https://private-user-images.githubusercontent.com/158049399/318238471-38e31419-6444-4325-b2a1-ea9cc9df0ad1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNDU4MzAsIm5iZiI6MTcxMjA0NTUzMCwicGF0aCI6Ii8xNTgwNDkzOTkvMzE4MjM4NDcxLTM4ZTMxNDE5LTY0NDQtNDMyNS1iMmExLWVhOWNjOWRmMGFkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMlQwODEyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTEzNzEyNmI3OTI1NjE5ZDNmM2M0MjE0MWJiMzUxODI4ODhlNjU4NjM1NmM4MDMyYjEyOGQxYTg1MjMyYjFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yONmFi-vj-39dUkENdE4NniTMLwJ0741pCbBxdi7cLY) 升级凯金和ZPM化工厂的话又需要凯金（

这个什么时候能修哇，LuV卡好久了（

**Comment by Arborsm** [comment]
早修了



---Original---
From: ***@***.***&gt;
Date: Tue, Apr 2, 2024 16:14 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [Arborsm/GT--] no recipe for Na2NO3 in ATM9 (Issue #4)




 
埃克森美孚化工厂的过氧化氢配方是不是有点问题（听别人说的

**Comment by Arborsm** [comment]
今晚看看



---Original---
From: ***@***.***&gt;
Date: Tue, Apr 2, 2024 16:16 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [Arborsm/GT--] no recipe for Na2NO3 in ATM9 (Issue #4)




  
我不知道这是不是我这里的问题（  LuV机械方块+硅岩线圈显示配方处理等级是IV，但是要产凯金的话要LuV  升级凯金和ZPM化工厂的话又需要凯金（
  
这个什么时候能修哇，LuV卡好久了（

**Comment by woetal** [comment]
感谢

**Comment by Arborsm** [comment]
嗯？似乎单纯是用错数据了显示错了，但是应该能跑配方吧?

**Comment by Arborsm** [comment]
![image](https://github.com/Arborsm/GT--/assets/44860537/5ee0f6c2-8cfb-475c-8665-9c5bed6e5aff)
确实没问题

**Comment by woetal** [comment]
啊？但是我的配方好像跑不了

**Comment by woetal** [comment]
我回去看看

**Comment by woetal** [comment]
![image](https://github.com/Arborsm/GT--/assets/158049399/6ab3bcb9-1d19-4eac-a1e8-ea17fe5acac4)
![image](https://github.com/Arborsm/GT--/assets/158049399/5beab1aa-83b2-4603-a742-7024c13defee)
![image](https://github.com/Arborsm/GT--/assets/158049399/2c789ef3-3849-4495-a146-a8b4b4e9eac9)
![image](https://github.com/Arborsm/GT--/assets/158049399/516c0629-b3e4-4f1a-802d-3a484f0fd29e)
![image](https://github.com/Arborsm/GT--/assets/158049399/bd26696a-dbe6-4dcd-99f0-88144e2871c2)
![image](https://github.com/Arborsm/GT--/assets/158049399/5837bf5e-ddda-476a-92e7-017642e7d0e4)
![image](https://github.com/Arborsm/GT--/assets/158049399/3b2479e9-34d7-46be-ab7c-b9883ccf6754)

**Comment by woetal** [comment]
这个输入输出配置有无问题

**Comment by woetal** [comment]
没问题了

**Comment by woetal** [comment]
找到问题了，是至少得要有四个输入输出仓才可以

**Comment by woetal** [comment]
> 找到问题了，是至少得要有四个输入输出仓才可以

这个配方还有个输出产物是氟锑酸，没显示出来，配方能跑，现在就是结构电压等级显示问题和配方输出物显示问题
