### ISSUE TITLE
GTNN is uncompatible with Ad astra/GTNN和Ad astra不兼容

### ISSUE THREAD

**Issue by spritoedmand** [Arborsm/ArborCore#5]
[crash-2024-03-24_18.13.26-client.txt](https://github.com/Arborsm/GT--/files/14734953/crash-2024-03-24_18.13.26-client.txt)

**Comment by Arborsm** [comment]
嗯？ 无法重现
![image](https://github.com/Arborsm/GT--/assets/44860537/f7363f73-b4d3-4064-ac67-0664f9280cd1)

**Comment by Arborsm** [comment]
gtm1.1.4 改了东西

**Comment by Arborsm** [comment]
修了  忘关了
