### ISSUE TITLE
gtnn、gcry和ad astra三者的兼容问题

### ISSUE THREAD

**Issue by Cynical1115** [Arborsm/ArborCore#6]
[crash-2024-03-27_18.56.57-client.txt](https://github.com/Arborsm/GT--/files/14772250/crash-2024-03-27_18.56.57-client.txt)
三者仅安装任意两者都可进入游戏，同时安装三者时会报错

**Comment by Arborsm** [comment]
> [crash-2024-03-27_18.56.57-client.txt](https://github.com/Arborsm/GT--/files/14772250/crash-2024-03-27_18.56.57-client.txt) 三者仅安装任意两者都可进入游戏，同时安装三者时会报错

这是gcyr的问题，我已经发pr修复了 但他们没发新版本
