### ISSUE TITLE
启动时崩溃

### ISSUE THREAD

**Issue by 4li77l3n00b** [Arborsm/ArborCore#7]
[crash-2024-04-17_12.34.35-client.txt](https://github.com/Arborsm/GT--/files/15005608/crash-2024-04-17_12.34.35-client.txt)
[latest.log](https://github.com/Arborsm/GT--/files/15005611/latest.log)

**Comment by Arborsm** [comment]
更新 https://modrinth.com/mod/gtnn/version/1.0.5

**Comment by 4li77l3n00b** [comment]
[crash-2024-04-17_14.10.30-fml.txt](https://github.com/Arborsm/GT--/files/15006624/crash-2024-04-17_14.10.30-fml.txt)
依然报错

**Comment by Arborsm** [comment]
gtm太新了 我只对正式版本做了兼容
